Models/Adventurer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuildRoom.Models {
    public class Adventurer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CharId { get; set; }
        public string CharName { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int Mana { get; set; }
        public Room Room { get; set; }

    public int SwordStrike()
    {
        return 10;
    }
    }
}

Models/ErrorViewModel.cs
using System;

namespace BuildRoom.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Monster.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuildRoom.Models {
    public class Monster
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MonsterId { get; set; }
        public string MonsterName { get; set; }
        public int Defense { get; set; }
    }
}

Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuildRoom.Models
{
    public class Room
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RoomId { get; set; }

        public string RoomName { get; set; }
        public int Width { get; set; }
        public int Length { get; set; }
        public string WallMaterial { get; set; }
        public string FloorMaterial { get; set; }
        public virtual List<Adventurer> Adventurers { get; set; }
    }
}

Controllers/AdventurerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using BuildRoom.Models;
using System.Collections.Generic;

namespace BuildRoom.Controllers
{
    public class AdventurerController : Controller
    {
        public ActionResult Index()
        {
            Adventurer NewAdventurer = new Adventurer();
            Monster Mob = new Monster();
            Room MyRoom = new Room();
            MyRoom.RoomName = "Entry";
            Mob.MonsterName = "Steve the Orc";
            NewAdventurer.CharName = "Eveehi";
            NewAdventurer.Attack = 10;
            NewAdventurer.Defense = 11;
            NewAdventurer.Mana = 7;
            MyRoom.Adventurers = new List<Adventurer>();
            MyRoom.Adventurers.Add(NewAdventurer);
            return View(MyRoom);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BuildRoom.Models;

namespace BuildRoom.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using BuildRoom.Models;

namespace BuildRoom.Controllers
{
    public class RoomController : Controller
    {
        public ActionResult Index()
        {
            var NewRoom = new Room();
            NewRoom.RoomName = "Entry";
            return View(NewRoom);
        }
        public string CreateRoom()
        {
            return "Create room here";
        }
        public string SingleRoom(string name, int width = 5)
        {
            return HtmlEncoder.Default.Encode($"Room Name: {name} - Width: {width}");
        }
    }
}

Views/Adventurer/Index.cshtml
@model BuildRoom.Models.Room

@{
    ViewData["Title"] = "Adventuer";
}

<h2>Adventurers</h2>

<p>Create Adventurers</p>
<p>Entering @Model.RoomName</p>
<p>Room Id = @Model.RoomId</p>
<p>@Model.Adventurers[0].CharName attacks: @Model.Adventurers[0].SwordStrike()</p>

Views/BuildRoom/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Build rooms</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Room/Index.cshtml
@model BuildRoom.Models.Room

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Build rooms</p>
<p>Room name @Model.RoomName</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuildRoom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BuildRoom</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Room</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Adventurer" asp-action="Index">Adventurer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BuildRoom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>